const express = require('express');
const User = require('../models/User');
const { userValidationMiddleware } = require('../middleware/validation');
const { EMAIL_REGEX, PASSWORD_REGEX, PASSWORD_MIN_LENGTH } = require('../utils/user/constants');
const STUDENT_ID = "33810672";
const STUDENT_NAME = "Viet Tran";

const router = express.Router();

// ============================================
// REGISTRATION ROUTE
// ============================================

// GET user registration page
// router.get(`/register-${STUDENT_ID}`, (req, res) => {
//     res.render('user/register', {
//         title: 'User Registration - CloudKitchen Pro',
//         formData: {}, // Pass an empty formData object
//     });
// });

// POST user registration - uses userValidationMiddleware
// router.post(`/register-${STUDENT_ID}`, userValidationMiddleware, async (req, res) => {
//     // If middleware attached validation errors, render registration page with errors
//     if (req.validationErrors && req.validationErrors.length > 0) {
//         return res.status(400).render('user/register', {
//             title: 'User Registration - CloudKitchen Pro',
//             errors: req.validationErrors,
//             formData: req.body
//         });
//     }

//     try {
//         // userId will be automatically generated by the pre-validate middleware
//         // Use validated data from user validation middleware
//         const newUser = new User(req.validatedUser);
//         await newUser.save();
//         return res.redirect(`/user/login-${STUDENT_ID}?msg=Registration successful! Please login with your new account.`);
//     } catch (err) {
//         const renderErrors = [];
//         if (err.name === 'ValidationError') {
//             for (const key in err.errors) {
//                 if (Object.prototype.hasOwnProperty.call(err.errors, key)) {
//                     renderErrors.push(err.errors[key].message);
//                 }
//             }
//         } else if (err.code === 11000 && err.keyValue && err.keyValue.email) {
//             renderErrors.push('Email address is already registered');
//         } else {
//             renderErrors.push('Failed to register user');
//         }

//         return res.status(400).render('user/register', {
//             title: 'User Registration - CloudKitchen Pro',
//             errors: renderErrors,
//             formData: req.body, // Preserve original form data for re-rendering
//         });
//     }
// });

// POST user registration - uses userValidationMiddleware
router.post(`/register-${STUDENT_ID}`, userValidationMiddleware, async (req, res) => {
    // Check for validation errors
    if (req.validationErrors && req.validationErrors.length) {
        // status 400: Bad Request
        return res.status(400).json({ errors: req.validationErrors });
    }
    // Proceed to create user
    try {
        // Get validated user data
        const data = req.validatedUser;

        // Check if user already exists by email, return conflict if so
        const exists = await User.findOne({ email: data.email });
        // status 409: Conflict
        if (exists) return res.status(409).json({ error: 'Email already registered' });

        // Create and save new user
        const newUser = new User(data);
        await newUser.save();

        // Return success response if user created successfully
        return res.status(201).json({ message: 'User registered', userId: newUser.userId });
    } catch (err) {
        // Handle server errors when handling registration
        console.error(err);
        // status 500: Internal Server Error
        return res.status(500).json({ error: 'Registration failed' });
    }
});

// ============================================
// LOGIN ROUTE
// ============================================
router.get(`/login-${STUDENT_ID}`, (req, res) => {
    res.render('user/login', {
        title: 'User Login - CloudKitchen Pro',
        formData: {}, // Pass an empty formData object
        msg: req.query.msg || '', // Pass message from query params
    });
});

// POST user login
router.post(`/login-${STUDENT_ID}`, async (req, res) => {
    try {
        const { email, password } = req.body;
        const trimmedEmail = email ? email.trim().toLowerCase() : "";

        // Email validation
        if (!trimmedEmail || !EMAIL_REGEX.test(trimmedEmail)) {
            return res.status(400).render('user/login', {
                title: 'User Login - CloudKitchen Pro',
                errors: ['Invalid email format.'],
                formData: req.body
            });
        }

        // Password validation
        if (!password || password.length < PASSWORD_MIN_LENGTH || !PASSWORD_REGEX.test(password)) {
            return res.status(400).render('user/login', {
                title: 'User Login - CloudKitchen Pro',
                errors: ['Password is required and must meet complexity requirements.'],
                formData: req.body
            });
        }

        // Find user by email (since email is unique)
        const user = await User.findOne({ email: trimmedEmail });

        // User not found
        if (!user) {
            return res.status(400).render('user/login', {
                title: 'User Login - CloudKitchen Pro',
                errors: ['Account not found.'],
                formData: req.body
            });
        }

        // Password mismatch
        if (user.password !== password) {
            return res.status(400).render('user/login', {
                title: 'User Login - CloudKitchen Pro',
                errors: ['Invalid credentials.'],
                formData: req.body
            });
        }

        // Login successful
        user.isLoggedIn = true;
        await user.save();

        // Redirect to home with userId
        return res.redirect(`/?userId=${user.userId}&msg=Successfully logged in`);
    } catch (err) {
        console.error('Login error:', err);
        return res.status(500).render('user/login', {
            title: 'User Login - CloudKitchen Pro',
            errors: ['An error occurred during login.'],
            formData: req.body
        });
    }
});

// ============================================
// LOGOUT ROUTE
// ============================================
router.get(`/logout-${STUDENT_ID}`, async (req, res) => {
    const { userId } = req.query;
    if (!userId) {
        return res.status(400).send('User ID required');
    }
    try {
        const user = await User.findOne({ userId });
        if (user) {
            user.isLoggedIn = false;
            await user.save();
        }
        // Redirect to home
        return res.redirect('/');
    } catch (err) {
        console.error('Logout error:', err);
        return res.status(500).send('Logout failed');
    }
});

module.exports = router;